# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  #name: Default
  vmImage: ubuntu-latest


variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

steps:
- task: Cache@2
  inputs:
    key: 'maven | "$(Agent.OS)" | $(Build.SourcesDirectory)/pom.xml'
    restoreKeys: |
      maven | "$(Agent.OS)"
      maven
    path: $(MAVEN_CACHE_FOLDER)
  displayName: Cache Maven local repo

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m $(MAVEN_OPTS)'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package'
  displayName: Build PetClinic App and Run unit tests


- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultworkingDirectory)/target'
    ArtifactName: 'petclinicwebapp'
    publishLocation: 'Container'
  displayName: 'Publish Build Artifacts'

- task: Docker@2
<<<<<<< HEAD
  displayName: 'Build Docker image'
  inputs:
    command: build
    repository: 'petclinicwebapp'
    dockerfile: 'Dockerfile'
    tags: |
      $(Build.BuildId)
=======
  displayName: 'Login to Docker Hub'
  inputs:
    containerRegistry: 'DevopsACRsyam'
    command: 'login'
- task: Docker@2
  displayName: 'Build and Push Docker image'
  inputs:
    containerRegistry: 'DevopsACRsyam'
    command: 'buildAndPush'
    repository: '$(dockerHubRepo)'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)'

>>>>>>> 22af06b4f408aa99cf416d69477df470bf5276ac







 
